on:
  workflow_dispatch:
    inputs:
      required_foobar:
        description: "required foobarzinho"
        required: true

      default_foobar:
        description: "default foobarzinho"
        required: true
        default: "default foobarzinho"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v4

      - id: setup-required-foobar
        uses: ./.github/test
        with:
          required_foobar: ${{ inputs.required_foobar }}
          default_foobar: ${{ inputs.default_foobar }}

      - id: run-stuff
        shell: bash
        run: echo barbaz ${{ steps.setup-required-foobar.outputs.barbaz }}
